### ISSUE TITLE
Getting only last sent notification(with expiration) after coming online

### ISSUE THREAD

**Issue by OmKessarwani** [urbanairship/phonegap-ua-push#180]
I have sent three(3) notification keeping my device offline, when I turned on network for device, then I received only one(1) notification, but badge count was 3.
Not sure why facing this error.

below are my setup details :
UA version : 6.6.0
Cordova version : 6.5.0
Cordova iOS : 4.3.1

**Comment by rlepinski** [comment]
How are you accessing the last notification? The plugin only supports getting the launch push, not previously received push notifications.

**Comment by rlepinski** [comment]
@OmKessarwani So this is standard APNS behavior. See https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html

> Apple Push Notification service includes a Quality of Service (QoS) component that performs a store-and-forward function. If APNs attempts to deliver a notification and the destination device is offline, APNs stores the notification for a limited period of time and delivers it when the device becomes available again. This component stores only the most recent notification per device and per app. If a device is offline, sending a notification request targeting that device causes the previous request to be discarded. If a device remains offline for a long time, all its stored notifications in APNs are discarded.

The badge count of 3 is most likely due to using our auto badging feature. The badge count is stored with Urban Airship, so it will increment 3 times and send down 3 on the last notification, the only one being delivered by Apple.

If you need more help, please visit https://support.urbanairship.com/
